name: lint-ros-package

on:
  workflow_call:
    inputs:
      python_version:
        default: "3.8"
        required: false
        type: string

jobs:
  changes:
    name: changes
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      cpp: ${{ steps.changes.outputs.cpp }}
      cpp_files: ${{ steps.changes.outputs.cpp_files }}
      python: ${{ steps.changes.outputs.python }}
      python_files: ${{ steps.changes.outputs.python_files }}
      cmake: ${{ steps.changes.outputs.cmake }}
      cmake_files: ${{ steps.changes.outputs.cmake_files }}
      yaml: ${{ steps.changes.outputs.yaml }}
      yaml_files: ${{ steps.changes.outputs.yaml_files }}
      xml: ${{ steps.changes.outputs.xml }}
      xml_files: ${{ steps.changes.outputs.xml_files }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: changed-file-filter
        id: changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: |
            cpp:
              - added|modified: '**.h'
              - added|modified: '**.hpp'
              - added|modified: '**.hh'
              - added|modified: '**.hxx'
              - added|modified: '**.c'
              - added|modified: '**.cpp'
              - added|modified: '**.cc'
              - added|modified: '**.cxx'
            python:
              - added|modified: '**.py'
            cmake:
              - added|modified: '**/CMakeLists.txt'
              - added|modified: '**.cmake'
            yaml:
              - added|modified: '**.yaml'
              - added|modified: '**.yml'
            xml:
              - added|modified: '**/launch/*(*/)*.launch'
              - added|modified: '**/launch/*(*/)*.xml'
              - added|modified: '**/package.xml'
              - added|modified: '**.xacro'
              - added|modified: '**.urdf'
          list-files: "shell"

  clang:
    name: runner / c++
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: changes
    if: needs.changes.outputs.cpp == 'true'
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Download config
        run: wget https://raw.githubusercontent.com/sbgisen/.github/main/.clang-format -O .clang-format
      - uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.18.2
        with:
          source: ${{ needs.changes.outputs.cpp_files }}
          exclude: ""
          extensions: "h,hpp,hh,hxx,c,cpp,cc,cxx"
          clangFormatVersion: 10
          style: file
          inplace: true
      - name: suggester / clang-format
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
        with:
          tool_name: clang-format
          filter_mode: file
          fail_on_error: true
  python:
    name: runner / python
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: changes
    if: needs.changes.outputs.python == 'true'
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python3 environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Download config
        run: wget https://raw.githubusercontent.com/sbgisen/.github/main/setup.cfg -O setup.cfg
      - name: autopep8 format
        uses: peter-evans/autopep8@921e8f57f62a70ba5dd9fac0d1f4834e4d819c22 # v1.2.2
        with:
          args: -i ${{ needs.changes.outputs.python_files }} --global-config setup.cfg
      - name: Restore config
        run: git diff --name-only | grep setup.cfg | xargs git checkout
      - name: suggester / autopep8
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
        with:
          tool_name: autopep8
          filter_mode: file
          fail_on_error: true
      - name: Setup reviewdog
        uses: reviewdog/action-setup@8f2ec89e6b467ca9175527d2a1641bbd0c05783b # v1.0.3
      - name: flake8 lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}/../
          wget https://raw.githubusercontent.com/sbgisen/.github/main/flake8_requirements.txt -O flake8_requirements.txt
          pip3 install -r flake8_requirements.txt
          cd ${{ github.workspace }}
          wget https://raw.githubusercontent.com/sbgisen/.github/main/setup.cfg -O setup.cfg
          file_list="${{ needs.changes.outputs.python_files }}"
          flake8 --select=E,F,W,C,N,I,ANN ${file_list} |\
          reviewdog -name="flake8" -reporter=github-pr-review -efm='%f:%l:%c: %*[^0-9]%n %m' \
          -filter-mode=file -fail-on-error
      - name: isort # ref #53
        run: |
          cd ${{ github.workspace }}/../
          pip3 install isort
          cd ${{ github.workspace }}
          file_list="${{ needs.changes.outputs.python_files }}"
          isort ${file_list}
          git diff --name-only | grep setup.cfg | xargs git checkout
      - name: suggester / isort
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
        with:
          tool_name: isort
          filter_mode: file
          fail_on_error: true
      - name: Lint docstrings
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}/../
          pip3 install flake8-docstrings
          cd ${{ github.workspace }}
          wget https://raw.githubusercontent.com/sbgisen/.github/main/setup.cfg -O setup.cfg
          file_list="${{ needs.changes.outputs.python_files }}"
          flake8 --select=D ${file_list} |\
          reviewdog -name="docstring" -level warning -reporter=github-pr-check \
          -efm='%f:%l:%c: %.%n %m' -filter-mode=file

  cmake:
    name: runner / cmake-format
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: changes
    if: needs.changes.outputs.cmake == 'true'
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Download config
        run: wget https://raw.githubusercontent.com/sbgisen/.github/main/.cmake-format -O .cmake-format
      - name: cmake-format
        run: |
          pip3 install cmake-format
          cmake-format -c .cmake-format -i ${{ needs.changes.outputs.cmake_files }}
          git diff --name-only | grep .cmake-format | xargs git checkout
      - name: suggester / cmake-format
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
        with:
          tool_name: cmake-format
          filter_mode: file
          fail_on_error: true
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: changes
    if: needs.changes.outputs.yaml == 'true'
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Download config
        run: wget https://raw.githubusercontent.com/sbgisen/.github/main/.yamllint -O .yamllint
      - name: yamllint
        uses: reviewdog/action-yamllint@8c429dfe4fc47b1ce1fa99a64e94693880d5dc30 # v1.6.1
        with:
          reporter: github-pr-review
          filter_mode: file
          fail_on_error: true
          yamllint_flags: -s -c .yamllint ${{ needs.changes.outputs.yaml_files }}
  xml:
    name: runner / xml
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: changes
    if: needs.changes.outputs.xml == 'true'
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup reviewdog
        uses: reviewdog/action-setup@8f2ec89e6b467ca9175527d2a1641bbd0c05783b # v1.0.3
      - name: xmllint roslaunch
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          sudo apt update
          sudo apt install libxml2-utils
          wget https://gist.githubusercontent.com/nalt/dfa2abc9d2e3ae4feb82ca5608090387/raw/roslaunch.xsd \
          -O roslaunch.xsd
          file_list="${{ needs.changes.outputs.xml_files }}"
          files=`echo ${file_list} | xargs -n 1 | grep -E ".*launch/.*\.(launch|xml)" || true`
          if [ -z ${files} ]; then
            echo "There are no launch files."
          else
            xmllint --noout --schema roslaunch.xsd ${files} 2>&1 1>/dev/null |\
            reviewdog -name="xmllint" -reporter=github-pr-review -efm='%f:%l:%m' -filter-mode=file -fail-on-error
          fi
      - name: xmllint package.xml
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          files=`echo ${{ needs.changes.outputs.xml_files }} | xargs -n 1 | grep -E ".*package.xml" || true`
          if [ -z ${files} ]; then
            echo "There are no package.xml files."
          else
            wget http://download.ros.org/schema/package_format2.xsd -O package_format2.xsd
            wget http://download.ros.org/schema/package_format3.xsd -O package_format3.xsd
            lint_result=/tmp/xmllint
            for file in ${files}
            do
              format_version=`cat $file | sed -En 's/<package format="(.*)">/\1/p'`
              xmllint --noout --schema package_format${format_version}.xsd $file 2>>${lint_result} | true
            done
            cat ${lint_result} |\
            reviewdog -name="xmllint" -reporter=github-pr-review -efm='%f:%l:%m' -filter-mode=file -fail-on-error
          fi
      - name: xmllint format
        run: |
          echo ${{ needs.changes.outputs.xml_files }} |\
          xargs -n 1 | xargs -I {} bash -c "xmllint --format {} |\
          diff -B {} - |\
          patch {}"
          git diff --name-only | grep "^package_format.\.xsd" | xargs git checkout
      - name: suggester / xmllint
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
        with:
          tool_name: xmllint
          filter_mode: file
          fail_on_error: true
