# This workflow enables developers to call PR-Agents `/[actions]` in PR's comments and upon PR creation.
# Learn more at https://www.codium.ai/pr-agent/

name: PR-Agent

on:
  workflow_call:
    inputs:
      common_extra_instructions:
        description: Common extra instructions. It will be used if the specific instructions are not provided.
        required: false
        type: string
        default: ""
      description_extra_instructions:
        description: Description extra instructions
        required: false
        type: string
        default: ""
      review_extra_instructions:
        description: Review extra instructions
        required: false
        type: string
        default: ""
      improve_extra_instructions:
        description: Improve extra instructions
        required: false
        type: string
        default: ""
    secrets:
      openai_key:
        required: true

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: PR Agent action step
        id: pr_agent
        uses: Codium-ai/pr-agent@b4458ffedef0ba09a618742a21b95b4b492dc5c7 # v0.21 + gpt-4o
        env:
          OPENAI_KEY: ${{ secrets.openai_key }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
          PR_DESCRIPTION.ADD_ORIGINAL_USER_DESCRIPTION: false
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMENT: true
          PR_REVIEWER.EXTRA_INSTRUCTIONS: |
            ${{ (inputs.review_extra_instructions != '' && inputs.review_extra_instructions) ||
            inputs.common_extra_instructions }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: |
            ${{ (inputs.improve_extra_instructions != '' && inputs.improve_extra_instructions) ||
            inputs.common_extra_instructions }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: |
            ${{ (inputs.description_extra_instructions != '' && inputs.description_extra_instructions) ||
            inputs.common_extra_instructions }}
          CONFIG.MODEL: gpt-4o
          CONFIG.MODEL_TURBO: gpt-4o
