# This workflow enables developers to call PR-Agents `/[actions]` in PR's comments and upon PR creation.
# Learn more at https://www.codium.ai/pr-agent/

name: PR-Agent

on:
  workflow_call:
    secrets:
      openai_key:
        required: true

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: PR Agent action step
        id: pr_agent
        uses: Codium-ai/pr-agent@fae6cab2a7e0791df7e9f9c8e702f3a052e9d261 # v0.21 + gpt-4-turbo
        env:
          OPENAI_KEY: ${{ secrets.openai_key }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
